apiVersion: serving.kubeflow.org/v1beta1
kind: InferenceService
metadata:
  name: stable-diffusion
spec:
  predictor:
    containerConcurrency: 1
    minReplicas: 0
    maxReplicas: 1
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: gpu.nvidia.com/class
              operator: In
              values:
              - A40
              - RTX_A6000
              - A100_PCIE_40GB
              - A100_PCIE_80GB
              - A100_NVLINK
              - Quadro_RTX_5000
            - key: node.coreweave.cloud/cpu
              operator: In
              values:
              - amd-epyc-milan
              - amd-epyc-rome
              - intel-xeon-scalable
              - intel-xeon-v4
            - key: topology.kubernetes.io/region
              operator: In
              values:
              - ORD1
              - LAS1
              - LGA1
    containers:
      - name: kserve-container
        image: nehavikas/stable_diffusion:1
        imagePullPolicy: Always
        env:
          - name: HUGGING_FACE_HUB_TOKEN
            valueFrom:
              secretKeyRef:
                name: huggingface-hub-token
                key: token
          - name: STORAGE_URI
            value: pvc://stable-diffusion-model-cache/
        resources:
          requests:
            cpu: 6
            memory: 32Gi
            nvidia.com/gpu: 1
          limits:
            cpu: 6
            memory: 32Gi
            nvidia.com/gpu: 1
